export const NAME = 'William Pham';
export const TITLE = 'Senior Software Engineer';
export const LOCATION = 'Ellenton, Florida';
export const TIME_ZONE = 'UTC-4'
export const EMAIL = 'huangcoderain@gmail.com'
export const EXPERIENCE = 13;
export const STACK = 'WEB and MOBILE development';
export const GITHUB = 'https://github.com/happydev521';
export const DISCORD = 'https://discord.com/users/code-rain#2249';
export const LINKEDIN = 'https://www.linkedin.com/in/william-h-fsdev/';
export const TELEGRAM = '';
export const FACEBOOK = '';
export const TWITTER = '';
